name: 'ype-infrastructure'

services:
  ype_reverse_proxy:
    container_name: ype_reverse_proxy
    build:
      context: ./nginx-proxy
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      VIRTUAL_HOST: ${VIRTUAL_HOST_PROXY}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST_PROXY}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/config:/etc/nginx/templates/:z
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - discourse_network
      - shared_net
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    networks:
      shared_net:
        aliases:
            - auth.uwu-ype.eu
    ports:
      - "8025:8025"     # http://localhost:8025 shows the inbox

  #ype_letsencrypt:
  #  image: jrcs/letsencrypt-nginx-proxy-companion
  #  container_name: ype_letsencrypt
  #  restart: always
  #  depends_on:
  #    - ype_reverse_proxy
  #  environment:
  #    NGINX_PROXY_CONTAINER: ype_reverse_proxy
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - ./nginx-proxy/certs:/etc/nginx/certs:rw
  #    - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
  #    - ./nginx-proxy/html:/usr/share/nginx/html
  #  read_only: true
  #  tmpfs:
  #    - /tmp
  #  security_opt:
  #    - no-new-privileges:true
  #  networks:
  #    - proxy

  #ype_docker_gen:
  #  image: jwilder/docker-gen
  #  container_name: ype_docker_gen
  #  restart: always
  #  command: >
  #    -notify-sighup ype_reverse_proxy
  #    -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  #  volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro
  #    - ./nginx-proxy/templates:/etc/docker-gen/templates
  #    - ./nginx-proxy/conf.d:/etc/nginx/conf.d
  #  read_only: true
  #  tmpfs:
  #    - /tmp
  #  security_opt:
  #    - no-new-privileges:true
  #  networks:
  #    - proxy

networks:
  shared_net:
    external: true
  discourse_network:
    external: true
  mailcow-network:
    external: true
