name: 'ype-infrastructure'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: always
    volumes:
      - nextcloud_data:/var/www/html/data
      - ./services/nextcloud/extra-apps:/var/www/html/custom_apps:rw
      - ./services/nextcloud/docker-entrypoint-hooks.d:/docker-entrypoint-hooks.d:ro
      - ./secrets/nextcloud-oidc-secret.txt:/run/secrets/nextcloud-oidc-secret:ro
    environment:
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${NEXTCLOUD_MYSQL_DATABASE}
      MYSQL_USER:     ${NEXTCLOUD_MYSQL_USER}
      MYSQL_HOST:     ${NEXTCLOUD_MYSQL_HOST}
      REDIS_HOST:     redis
      REDIS_HOST_PORT: 6379
      NEXTCLOUD_ADMIN_USER:     ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      OVERWRITEHOST:           ${NEXTCLOUD_OVERWRITEHOST}
      OVERWRITEPROTOCOL:       ${NEXTCLOUD_OVERWRITEPROTOCOL}
      OVERWRITECLIURL:         https://${NEXTCLOUD_TRUSTED_DOMAINS}
      VIRTUAL_HOST_NEXTCLOUD:  ${VIRTUAL_HOST_NEXTCLOUD}
      LETSENCRYPT_HOST:        ${LETSENCRYPT_HOST_NEXTCLOUD}
      LETSENCRYPT_EMAIL:       ${LETSENCRYPT_EMAIL}
      OIDC_CLIENT_SECRET_FILE: /run/secrets/nextcloud-oidc-secret
      OIDC_CLIENT_ID: nextcloud
      VIRTUAL_HOST_KEYCLOAK: ${VIRTUAL_HOST_KEYCLOAK}
      KEYCLOAK_REALM: example-realm
    networks:
      - proxy
      - shared_net
    depends_on:
      - db
      - redis
    secrets:
      - nextcloud-oidc-secret
    extra_hosts:
      - "auth.uwu-ype.eu:172.18.0.8"
  db:
    image: mariadb:11.7.2
    container_name: nextcloud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${NEXTCLOUD_MYSQL_DATABASE}
      MYSQL_USER:          ${NEXTCLOUD_MYSQL_USER}
      MYSQL_PASSWORD:      ${NEXTCLOUD_MYSQL_PASSWORD}
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks:
      - shared_net

  redis:
    image: redis:7-alpine
    container_name: nextcloud_redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - nextcloud_redis:/data
    networks:
      - shared_net

networks:
  shared_net:
    external: true
  proxy:
    external: true

volumes:
  nextcloud_data:
  nextcloud_db:
  nextcloud_redis:

secrets:
  nextcloud-oidc-secret:
    file: ./secrets/nextcloud-oidc-secret.txt
